#!/bin/sh

# This script is inspired by the wonderful people over at https://github.com/thoughtbot/laptop

function get_color() {

  if test -z "$1"; then
    echo "\e[0m"
  elif [ $1 == "FORMAT_ERROR" ]; then
    echo "\e[31m"
  elif [ $1 == "FORMAT_SUCCESS" ]; then
    echo "\e[32m"
  elif [ $1 == "FORMAT_WARNING" ]; then
    echo "\e[33m"
  else
    echo "\e[0m"
  fi
}

function fancy_echo() {
  local message="$1"
  local format_color=$(get_color "$2")
  printf "\\n$format_color $message\\n\e[0m"
}

function append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\\n" "$text" >>"$zshrc"
    else
      printf "\\n%s\\n" "$text" >>"$zshrc"
    fi
  fi
}

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
  fancy_echo "sucessfully added .bin directory" "FORMAT_SUCCESS"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
  fancy_echo "sucessfullt added created .zshrc file" "FORMAT_SUCCESS"
fi

append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

# Determine Homebrew prefix
arch="$(uname -m)"
if [ "$arch" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  append_to_zshrc "# Set PATH, MANPATH, etc., for Homebrew." 1
  append_to_zshrc "eval \"\$($HOMEBREW_PREFIX/bin/brew shellenv)\""

  export PATH="$HOMEBREW_PREFIX/bin:$PATH"
fi

brew bundle --file=- <<EOF
#Applications
cask "google-chrome"
cask "firefox"
cask "visual-studio-code"

# Node
brew "nvm"

# Image manipulation
brew "imagemagick"

# Useful utilities
brew "youtube-dl"
EOF

append_to_zshrc "export NVM_DIR=\"\$HOME/.nvm\""
append_to_zshrc "# This loads nvm" 1
append_to_zshrc "[ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"" 1
append_to_zshrc "# This loads nvm bash_completion" 1
append_to_zshrc "[ -s \"\$NVM_DIR/bash_completion\" ] && \. \"\$NVM_DIR/bash_completion\"" 1

nvm install node
